# Não roda automaticamente quando dá push
trigger: none
pr: none

parameters:
  - name: ambiente
    displayName: "Escolha o ambiente"
    type: string
    default: "STG"
    values:
      - STG
      - PRD

  - name: cenario
    displayName: "Qual cenário deseja rodar?"
    type: string
    default: "login.cy.js"
    values:
      - login.cy.js
      - cadastro.cy.js
      - homeBNE.cy.js
      - homeBNECIA.cy.js
      - telaATS.cy.js
      - footerEmpresas.cy.js
      - footerInstitucional.cy.js
      - pesquisarCurriculoBNE.cy.js
      - siteTrabalheConosco.cy.js
      - meusCurriculos.cy.js
      - configuracoes.cy.js
      - planos.cy.js

pool:
  vmImage: 'ubuntu-latest'

steps:
  - script: |
      export TERM=xterm
      echo "=== Rodando spec: ${{ parameters.cenario }} no ambiente ${{ parameters.ambiente }} ==="

      cd BNE_CIA_cypress
      npm install
      mkdir -p cypress/reports

      # Executa o Cypress (usa reporter definido no config.js)
      npx cypress run \
        --spec "cypress/e2e/${{ parameters.cenario }}" \
        --env ENV=${{ parameters.ambiente }} \
        --browser electron || echo "⚠️⚠️Testes falharam, mas o pipeline vai continuar. Verificar falhas nos testes!⚠️⚠️"

    displayName: "Executar testes Cypress e gerar relatório HTML"
    continueOnError: true

  # Publicar o relatório HTML como artefato no Azure DevOps
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'BNE_CIA_cypress/cypress/reports'
      ArtifactName: 'CypressReport'
      publishLocation: 'Container'
    displayName: "📦 Publicar relatório HTML do Cypress"
